//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentHouseManager.Project.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAOCAONGQUANLY
    {
        public string IDNGQUANLY { get; set; }
        public string NOIDUNG { get; set; }
    
        public virtual NGQUANLY NGQUANLY { get; set; }
    }
}
