//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentHouseManager.Project.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHUTRO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHUTRO()
        {
            this.IDRLSSes = new HashSet<IDRLSS>();
            this.QHPHGs = new HashSet<QHPHG>();
        }
    
        public string IDCHUTRO { get; set; }
        public string HOTEN { get; set; }
        public string CMND { get; set; }
        public System.DateTime NGAYSINH { get; set; }
        public string QUEQUAN { get; set; }
        public string EMAIL { get; set; }
        public string SDT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IDRLSS> IDRLSSes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QHPHG> QHPHGs { get; set; }
    }
}
