//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentHouseManager.Project.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IDRLSS
    {
        public string IDUSER { get; set; }
        public string IDPHANQUYEN { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual CHUTRO CHUTRO { get; set; }
        public virtual NGQUANLY NGQUANLY { get; set; }
        public virtual NGTHUE NGTHUE { get; set; }
    }
}
