//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentHouseManager.Project.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHONG()
        {
            this.QHPHGs = new HashSet<QHPHG>();
            this.DAYTROes = new HashSet<DAYTRO>();
        }
    
        public string IDPHONG { get; set; }
        public string CHATLUONGPHG { get; set; }
        public double DIENTICH { get; set; }
        public int PHONGTRONG { get; set; }
        public int SONGTOIDA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QHPHG> QHPHGs { get; set; }
        public virtual TIEN TIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAYTRO> DAYTROes { get; set; }
    }
}
