//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentHouseManager.Project.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class QHPHG
    {
        public string IDPHONG { get; set; }
        public string IDNGTHUE { get; set; }
        public string IDNGQUANLY { get; set; }
        public string IDCHUTRO { get; set; }
        public string IDDAYTRO { get; set; }
    
        public virtual CHUTRO CHUTRO { get; set; }
        public virtual DAYTRO DAYTRO { get; set; }
        public virtual NGQUANLY NGQUANLY { get; set; }
        public virtual NGTHUE NGTHUE { get; set; }
        public virtual PHONG PHONG { get; set; }
    }
}
